config/routes.rb
Rails.application.routes.draw do

  match '/404', to: 'errors#not_found', via: :all
  match '/505', to: 'errors#internal_server_error', via: :all

  devise_for :users, controllers: { registrations: 'registrations' }

  # /comprar (for orders:new)
  resources :orders, except: :new
  match '/comprar', to: 'orders#new', as: :new_order, via: :get

  # message creation route
  resources :messages, only: [:create, :index]

  # notifications
  resources :notifications do
    collection do
      post :mark_as_read
      get :count
    end
  end

  # .../admin/...
  namespace :admin do
    match '/', to: 'dashboard#index', via: :get
    match '/admins', to: 'dashboard#admins', via: :get

    # manage Users, Settings, Account Holders
    
    resources :users

    resources :settings, only: [:index, :update]
    resource :settings, only: [] do 
      post :update_all, on: :member
    end

    resources :account_holders
    
    resources :cards

    # manage Payment Methods + state toggle
    resources :payment_methods do
      collection do
        get 'toggle/:id' => :toggle, as: :toggle
      end
    end

    # manage Orders + history page
    resources :orders do
      collection do
        get 'history' => :history, as: :history
      end
    end

    # manage Orders > Accounts + state toggle
    resources :banks do
      collection do
        get 'toggle/:id' => :toggle, as: :toggle
      end

      resources :accounts do
        collection do
          get 'toggle/:id' => :toggle, as: :toggle
        end
      end
    end
  end

  # logged in  -> account page (orders:index)
  # logged out -> statice home page
  root to: 'pages#home'

  # static pages
  get '/home', to: 'pages#home', as: :home
  get '/instrucciones', to: 'pages#howto', as: :howto
  get '/legal', to: 'pages#legal', as: :legal
  get '/preguntas', to: 'pages#faq', as: :faq
  get '/contacto', to: 'pages#contact', as: :contact
  post '/contacto', to: 'pages#send_message', as: :contact_forms

end

app/models/account.rb
class Account < ApplicationRecord

  default_scope { order(created_at: :desc) }
  default_scope { where(deprecated: false) }

  validates :number, length: { minimum: 10 }
  validates :clabe, length: { is: 18 }, allow_blank: true

  validates :holder, presence: true
  validates :active, presence: true
  validates :bank, presence: true

  belongs_to :bank
  has_many :cards, dependent: :destroy
  has_and_belongs_to_many :payment_methods

  def name
    "#{self.bank.name} - #{self.number}"
  end

  def number_of_orders
    Order.where(account_id: self.id).count
  end

  def is_being_used
    self.payment_methods.count > 0
  end

end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < Admin::BaseController

  before_action :set_bank
  before_action :set_account, only: [:edit, :update, :destroy, :toggle]

  def index
    @accounts = @bank.accounts.all
  end

  def new
    @account = @bank.accounts.new
  end

  def edit
    @account_holders = AccountHolder.all
  end

  def create
    @account = @bank.accounts.create(account_params)
    if @account.save
      flash[:notice] = "La cuenta fue creada exitosamente."
      redirect_to edit_admin_bank_account_path @bank.id, @account.id 
    else
      render :new
    end
  end

  def update
    if params[:account][:deprecated] == "true"
      @account.update_attributes(deprecated: true)
      return redirect_to admin_banks_path(@bank), notice: 'La cuenta ya no aparecerá'
    end
    
    if @account.update_attributes(account_params)
      flash[:notice] = "Los cambios fueron guardados."
      redirect_to edit_admin_bank_account_path @bank, @account 
    else
      render :edit
    end
  end

  def toggle
    # direct db update
    @account.toggle!(:active)
    redirect_to :back
  end

  def destroy
    @account.destroy
    redirect_to admin_bank_accounts_path @bank
  end

  private

    def set_bank
      @bank = Bank.find(params[:bank_id])
    end

    def set_account
      @account = @bank.accounts.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:number, :clabe, :holder, :bank_id, :active, :deprecated)
    end

end

app/helpers/accounts_helper.rb
module AccountsHelper
  
  def holders
    AccountHolder.all.pluck(:name)
  end

end

app/views/admin/accounts/_cards.html.erb
<% @account.cards.each do |card| %>

  <%= form_for [:admin, card] do |f| %>
    <div class="form-group">
      <label>
        Número
        <% if card.is_being_used %>
          <small class="text-muted">En uso</small>
        <% end %>
      </label>
      <%= f.text_field :number, class: 'form-control' %>
    </div>

    <div class="actions">
      <div class="checkbox" style="display: inline">
        <label>
          <%= f.check_box :active %>
          <label>Activo</label>
        </label>
      </div>
      <div class="btn-group float-right">
        <%= f.submit 'Guardar', class: 'btn btn-sm btn-success' %>
        <% if !card.is_being_used and card.number_of_orders == 0 %>
          <%= link_to 'Eliminar', admin_card_path(card),
              method: :delete, class: 'btn btn-sm btn-danger',
              data: { confirm: 'Estás seguro?' } %>
        <% elsif !card.is_being_used %>
          <%= link_to 'Desaprobar', '#', class: 'btn btn-sm btn-secondary' %>
        <% end %>
      </div>
      <br />
    </div>
  <% end %>

<% end %>

<% if @account.cards.count == 0 %>
  <small class="muted">Actualmente ésta cuenta no tiene tarjetas asociadas.</small>
<% end %>

<hr />
<p>Agregar tarjeta asociada</p>

<%= form_for [:admin, @account.cards.new] do |f| %>
  <%= f.hidden_field :account_id %>

  <div class="form-group">
    <label>Número</label>
    <%= f.text_field :number, class: 'form-control' %>
  </div>

  <div class="actions">
    <div class="checkbox" style="display: inline">
      <label>
        <%= f.check_box :active %>
        <label>Activo</label>
      </label>
    </div>
    <%= f.submit 'Guardar', class: 'btn btn-sm btn-success float-right' %>
  </div>
<% end %>

app/views/admin/accounts/_delete.html.erb
<hr />

<small><p class="text-muted"><b>Eliminación de la cuenta</b></p></small>
<% if account.number_of_orders == 0 and !account.is_being_used %>
  <p><%= link_to 'Eliminar cuenta', admin_bank_account_path(account.bank, account),
    method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Estás seguro?' } %></p> 
<% elsif !account.is_being_used %>
  <small>
    <p>Esta cuenta ya tiene pedidos realizados, no se puede eliminar de la base de datos pero se puede esconder de las cuentas disponibles.</p>
  </small> 
  <%= link_to 'Esconder cuenta', admin_bank_account_path(account.bank, account, account: { deprecated: true }),
      method: :put, class: 'btn btn-sm btn-secondary' %>
<% else %>
  <small>
    <p>Esta cuenta está asociada a un método de pago, y por lo tanto no se puede eliminar ni esconder.</p>
  </small>        
<% end %>

app/views/admin/accounts/_form.html.erb
<%= simple_form_for([:admin, account.bank, account],
                    defaults: { wrapper_html: { class: 'field' } }, 
                    html: { class: 'form' }) do |f| %>

  <%= f.error :base %>

  <div class="form-group">                  
    <%= f.input :number, autofocus: true, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">                  
    <%= f.input :clabe, input_html: { class: 'form-control' } %>
  </div>
  <hr>
  
  <div class="form-group">
    <%= f.input :holder, as: :select, collection: holders %>    
  </div>  
  
  <div class="form-check">
    <label class="form-check-label">
      <%= f.check_box :active, class: 'form-check-input' %>
      <%= f.label :active %>
    </label>
  </div>

  <div class="form-group">                  
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>  

<% end %>

app/views/admin/accounts/edit.html.erb
<% title 'Cuentas' %>

<p class="page"><i class="fa fa-bank"></i> Bancos</p>

<nav class="breadcrumb">
  <a href="<%= admin_banks_path %>" class="breadcrumb-item">
    <i class="fa fa-angle-left"></i> bancos
  </a>
  <a href="<%= admin_bank_accounts_path(@bank) %>" class="breadcrumb-item"><b><%= @bank.name %></b></a>
  <span class="breadcrumb-item active">Editar cuenta</span>
</nav>

<div class="row justify-content-lg-center">
  <div class="col-lg-6">
    <%= render 'form', account: @account %>

    <%= render 'delete', account: @account %>
  </div>

  <div class="col-lg-6">
    <p>Tarjetas asociadas</p>
    <hr />

    <div class="cards">
      <%= render 'admin/accounts/cards' %>
    </div>
  </div>
</div>

app/views/admin/accounts/index.html.erb
<% title 'Cuentas' %>

<p class="page"><i class="fa fa-bank"></i> Bancos</p>

<nav class="breadcrumb">
  <a href="<%= admin_banks_path %>" class="breadcrumb-item">
    <i class="fa fa-angle-left"></i> bancos
  </a>
  <span class="breadcrumb-item active"><b><%= @bank.name %></b></span>
  <span class="breadcrumb-item active">cuentas</span>
</nav>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Número</th>
        <th>Holder</th>
        <th>Activo</th>
        <th># de tarjetas</th>
        <th># de pedidos</th>
      </tr>
    </thead>

    <tbody>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= link_to account.number, edit_admin_bank_account_path(account.bank, account) %></td>
          <td><%= account.holder %></td>
          <td>
            <%=
              render 'admin/shared/status_toggle',
                object: account,
                path: toggle_admin_bank_accounts_path(bank_id: @bank.id, id: account.id) %>
          </td>
          <td><%= account.cards.count %></td>
          <td><%= account.number_of_orders %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<a href="<%= new_admin_bank_account_path %>" class="nav-link">
  <i class="fa fa-plus"></i> cuenta nueva
</a>

app/views/admin/accounts/new.html.erb
<% title 'Cuentas' %>

<p class="page"><i class="fa fa-bank"></i> Bancos</p>

<nav class="breadcrumb">
  <a href="<%= admin_banks_path %>" class="breadcrumb-item">
    <i class="fa fa-angle-left"></i> bancos
  </a>
  <a href="<%= admin_bank_accounts_path(@bank) %>" class="breadcrumb-item"><b><%= @bank.name %></b></a>
  <span class="breadcrumb-item active">cuenta nueva</span>
</nav>

<div class="row justify-content-lg-center">
  <div class="col-lg-6">
    <%= render 'form', account: @account %>
  </div>
</div>