config/routes.rb
Rails.application.routes.draw do

  match '/404', to: 'errors#not_found', via: :all
  match '/505', to: 'errors#internal_server_error', via: :all

  devise_for :users, controllers: { registrations: 'registrations' }

  # /comprar (for orders:new)
  resources :orders, except: :new
  match '/comprar', to: 'orders#new', as: :new_order, via: :get

  # message creation route
  resources :messages, only: [:create, :index]

  # notifications
  resources :notifications do
    collection do
      post :mark_as_read
      get :count
    end
  end

  # .../admin/...
  namespace :admin do
    match '/', to: 'dashboard#index', via: :get
    match '/admins', to: 'dashboard#admins', via: :get

    # manage Users, Settings, Account Holders
    
    resources :users

    resources :settings, only: [:index, :update]
    resource :settings, only: [] do 
      post :update_all, on: :member
    end

    resources :account_holders
    
    resources :cards

    # manage Payment Methods + state toggle
    resources :payment_methods do
      collection do
        get 'toggle/:id' => :toggle, as: :toggle
      end
    end

    # manage Orders + history page
    resources :orders do
      collection do
        get 'history' => :history, as: :history
      end
    end

    # manage Orders > Accounts + state toggle
    resources :banks do
      collection do
        get 'toggle/:id' => :toggle, as: :toggle
      end

      resources :accounts do
        collection do
          get 'toggle/:id' => :toggle, as: :toggle
        end
      end
    end
  end

  # logged in  -> account page (orders:index)
  # logged out -> statice home page
  root to: 'pages#home'

  # static pages
  get '/home', to: 'pages#home', as: :home
  get '/instrucciones', to: 'pages#howto', as: :howto
  get '/legal', to: 'pages#legal', as: :legal
  get '/preguntas', to: 'pages#faq', as: :faq
  get '/contacto', to: 'pages#contact', as: :contact
  post '/contacto', to: 'pages#send_message', as: :contact_forms

end

app/models/order.rb
require 'bitcoin'

class Order < ApplicationRecord

  default_scope { order(created_at: :desc) }
  
  has_many :messages, dependent: :delete_all

  belongs_to :payment_method
  belongs_to :user

  validates :user, presence: true
  validates :payment_method_id, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :price, presence: true

  validate :valid_btc_address

  mount_uploaders :attachments, AttachmentUploader

  before_create :add_expires_at
  before_create :round_amount

  # order status, depending on a variety of situations
  def status
    if completed
      'Completado'
    elsif submitted
      'En proceso de revisión'
    elsif removed
      'Cancelado'
    elsif expired
      'Expirado'
    else
      'Esperando el pago y/o evidencia'
    end
  end

  # rounded price
  def total
    (amount * price).round(2)
  end

  # true/false if expired
  def expired
    return DateTime.now.utc > expires_at.utc
  end

  # is it canceled?
  def canceled
    removed
  end

  # Messages

  # unread by user?
  def new_message_for_user?
    messages.each do |msg|
      if !msg.user_read
        return true
      end
    end
    return false
  end

  # unread by admin?
  def new_message_for_admin?
    messages.each do |msg|
      if !msg.admin_read
        return true
      end
    end
    return false
  end

  # authorized_by
  def completed_by
    if authorized_by != nil
      User.find(authorized_by)
    else
      'Not completed'
    end
  end

  # Validator
  def valid_btc_address
    if address and !Bitcoin.valid_address? address
      errors.add(:address, 'No es un wallet valido.')
    end
  end

  private

    def add_expires_at
      self.expires_in = self.payment_method.expires
      self.expires_at = DateTime.now.utc + self.expires_in.hours
    end

    def round_amount
      self.amount = self.amount.round(8)
    end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    # only get new/pending orders
    @new_orders = Order.where(submitted: false, completed: false, removed: false)
    @pending_orders = Order.where(submitted: true, completed: false, removed: false)
    @expired_orders = Order.
                        where(submitted: false, completed: false, removed: true).
                        where('created_at > ?', Time.now - 1.day)
  end

  def history
    @orders = Order.where(completed: true).paginate(page: params[:page], per_page: 30)
  end

  def show
    # mark all messages as admin_read
    read_msgs @order
    if !@order.account_id.blank?
      @account = Account.unscoped.find(@order.account_id)
    end
    if !@order.card_id.blank?
      @card = Card.unscoped.find(@order.card_id)
    else
      @card = nil
    end
  end

  def update
    if params[:complete]
      # if the order is now complete
      @order.update_attributes(
        completed: true,
        authorized_by: current_user.id,
        completed_at: DateTime.now.utc
      )

      # notify user
      Notification.create(recipient: @order.user, action: 'completed', notifiable: @order)
      UserMailer.order_complete(@order).deliver_later

      redirect_to admin_order_path(@order),
        flash: { notice: "El pedido ##{@order.id} fue completado." }

    elsif params[:reject]
      # if not, then it's being rejected
      tolerance = DateTime.current + 1.hour
      @order.update_attributes(submitted: false, expires_at: tolerance)

      # notify user
      Notification.create(recipient: @order.user, action: 'rejected', notifiable: @order)
      UserMailer.order_denied(@order).deliver_later

      redirect_to admin_order_path(@order)
    else
      @order.update_attributes(order_params)
      redirect_to admin_order_path(@order)
    end
  end

  def destroy
    Notification.where(notifiable: @order).each do |notif|
      notif.destroy
    end
    @order.destroy
    if !@order.removed
      # notify the user if it wasn't previously cancelled by him
      Notification.create(recipient: @order.user, action: 'cancelled', notifiable: @order)
    end
    redirect_to admin_orders_path, flash: { notice: 'El pedido fue cancelado.' }
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    # update :admin_read
    def read_msgs order
      last_msgs = @order.messages.where(admin_read: false)
      last_msgs.each do |msg|
        msg.update_attributes(admin_read: true)
      end
    end

    def order_params
      params.require(:order).permit(:confirmed_account_id, :confirmed_card_id, :expires_at, :removed)
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  include OrdersHelper

  before_action :authenticate_user!

  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_btc_price, only: [:new, :create]

  # check if SITE is live and selling
  before_action :system_ok, only: [:new, :create, :update]
  
  # redirect to order if the user has an open order
  before_action :has_pending_order, only: [:new, :create]

  # user's account page
  def index
    @history = current_user.orders.where(completed: true, removed: false)
    @order = current_user.orders.where(completed: false, removed: false).first

    # if the user has a pending order, has not submitted evidence
    # and is expired, then 'delete' the order, and notify the user
    if @order and @order.expired and !@order.submitted
      Notification.create(
        recipient: @order.user,
        action: 'expired',
        notifiable: @order
      )
      #@order.destroy
      @order.update_attributes(removed: true)
      @order = nil
    end
  end

  # order receipt
  def show
    # if the GET request came from a notification click
    if params[:clear_notifs]
      Notification.where(notifiable_id: @order.id).update_all(read_at: Time.zone.now)
    end

    # mark all messages as read
    read_msgs @order
    
    # it's annoying having to write @order.payment_methods.each...
    @pm = @order.payment_method
  end

  def new
    @order = current_user.orders.new
    
    # set the current global variables and options
    @packs = Setting.packs || '0.01, 0.02, 0.05, 0.1'
    @packs = @packs.delete(' ').split(',').map(&:to_f)
    @methods = PaymentMethod.where(active: true, deprecated: false)
    @min = Setting.min
    @max = Setting.max
    @first_min = Setting.first_min
    @first_max = Setting.first_max
  end

  def create
    @order = current_user.orders.new(order_params)
    # set price from db always
    @order.price = get_price(@order.amount)

    if @order.save
      AdminMailer.new_order(@order).deliver_later
      redirect_to @order, notice: 'Tu pedido fue creado exitosamente.'
    else
      render :new
    end
  end

  def update
    # not pretty but the most user intuitive way I could come up with...
    if params[:step] == 'image'
      # user uploaded an image, just save and reload
      if order_params[:attachments] == nil
        redirect_to @order, alert: 'Debes subir la evidencia de pago en un formato válido.'
      else
        if @order.update(order_params)
          redirect_to @order, alert: 'Excelente. Ahora solo agrega tu domicilio wallet para completar el pedido.'
        else
          # redirect_to @order, alert: 'Hubo un error.'
          if @order.errors[:attachments].count > 0
            redirect_to @order, alert: 'El archivo es demasiado pesado. Debe ser menos de 2 MB. Intente de nuevo.'
          else
            redirect_to @order
          end  
        end
      end 
    else
      # user added his wallet address
      if order_params[:address] == nil
        # safe checking for empty address
        redirect_to @order, alert: 'Debes poner un domicilio válido.'
      elsif @order.attachments.count == 0
        # the user hasn't uploaded an image, but save the address
        address_params = order_params
        address_params[:submitted] = false
        @order.update(address_params)
        redirect_to @order, alert: 'Debes subir una imagen de tu evidencia (paso 2).'
      elsif @order.update(order_params)
        # order is completed
        AdminMailer.order_submitted(@order).deliver_later
        redirect_to @order, notice: 'Tu pago ahora está en proceso de revisión.'
      end
    end
  end

  def destroy
    # destroy all current notifications
    Notification.where(notifiable_id: @order.id).delete_all

    # destroy order
    @order.update_attributes(removed: true)

    # notify the admin that the order was cancelled
    AdminMailer.order_cancelled().deliver_later
    redirect_to orders_url, notice: 'Tu pedido fue cancelado.'
  end

  private

    def set_order
      @order = current_user.orders.find(params[:id])
    end

    def order_params
      params.require(:order).permit(
        :amount, :price, :address,
        :submitted, :payment_method_id,
        {attachments: []}, :account_id, :card_id
      )
    end

    def set_btc_price
      @btc_display_price = Setting.display_price
      @btc_prices = Setting.prices
    end

    # if he has a pending order, redirect to it
    def has_pending_order
      if current_user.active_orders_count > 0
        redirect_to current_user.orders.first,
          flash: { notice: 'Tienes un pedido pendiente.' }
      end
    end

    # update :user_read
    def read_msgs order
      last_msgs = order.messages.where(user_read: false)
      last_msgs.each do |msg|
        msg.update_attributes(user_read: true)
      end
    end

    def system_ok
      if Setting.active != '1'
        render 'orders/not_active'
      end
    end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper

  def btc_amount(n)
    n.round(5)
  end

  def accounts_collection(add_empty = nil)
  	accounts = Account.all.collect { |a| [a.name, a.id] }
  	accounts << ['Otro', ''] if add_empty
  	return accounts
  end

  def cards_collection(add_empty = nil)
  	cards = Card.all.collect { |a| [a.number, a.id] }
  	cards << ['Otro', ''] if add_empty
  	return cards
  end

end

app/helpers/orders_helper.rb
module OrdersHelper

  def get_price amount
    @btc_prices.reverse.each do |price|
      if amount > price[:minb]
        return price[:price]
      end
    end
  end

end

app/views/admin/orders/_expired.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Cuando</th>
        <th>Usuario</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th>Método de pago</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @expired_orders.each do |order| %>
        <tr>
          <td><%= link_to formatted_date(order.created_at), admin_order_path(order) %></td>
          <td><%= order.user.email %></td>
          <td><%= btc_amount(order.amount) %></td>
          <td><%= order.price %></td>
          <td><%= order.payment_method.name %></td>
          <td><%= render 'admin/orders/message_count', order: order %></td>
          <td>
            <center>
              <%= link_to 'Revisar', admin_order_path(order), class: 'ui mini button' %>
            </center>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% if @expired_orders.count == 0 %>
  <div class="alert alert-secondary">
    No existen pedidos expirados recientes (< dos días).
  </div>
<% end %>

app/views/admin/orders/_message_count.html.erb
<center>
  <% if current_user.admin? %>
    <a href="<%= admin_order_path(order) %>">
      <% if order.new_message_for_admin? %>
        <div class="badge badge-danger">
      <% else %>
        <div class="badge badge-default">
      <% end %>
          <i class="fa fa-comments"></i> <%= order.messages.count %>
        </div>
    </a>
  <% else %>
    <a href="<%= order_path(order) %>">
      <% if order.new_message_for_user? %>
        <div class="badge badge-danger">
      <% else %>
        <div class="badge badge-default">
      <% end %>
          <i class="fa fa-comments"></i> <%= order.messages.count %>
        </div>
    </a>
  <% end %>
</center>

app/views/admin/orders/_new.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Cuando</th>
        <th>Usuario</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th>Método de pago</th>
        <th>Se expira</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @new_orders.each do |order| %>
        <% if !order.expired %>
          <tr>
            <td><%= link_to formatted_date(order.created_at), admin_order_path(order) %></td>
            <td><%= order.user.email %></td>
            <td><%= btc_amount(order.amount) %></td>
            <td><%= order.price %></td>
            <td><%= order.payment_method.name %></td>
            <td><%= formatted_date(order.expires_at) %></td>
            <td><%= render 'admin/orders/message_count', order: order %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<% if @new_orders.map.count == 0 %>
  <div class="alert alert-secondary">
    No tienes pedidos nuevos.
  </div>
<% end %>

app/views/admin/orders/_pending.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Cuando</th>
        <th>Usuario</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th>Método de pago</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @pending_orders.each do |order| %>
        <tr>
          <td><%= link_to formatted_date(order.created_at), admin_order_path(order) %></td>
          <td><%= order.user.email %></td>
          <td><%= btc_amount(order.amount) %></td>
          <td><%= order.price %></td>
          <td><%= order.payment_method.name %></td>
          <td><%= render 'admin/orders/message_count', order: order %></td>
          <td>
            <center>
              <%= link_to 'Revisar', admin_order_path(order), class: 'ui mini button' %>
            </center>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% if @pending_orders.count == 0 %>
  <div class="alert alert-secondary">
    No tienes pedidos pendientes.
  </div>
<% end %>

app/views/admin/orders/history.html.erb
<% title 'Historial de pedidos' %>

<p class="page"><i class="fa fa-bitcoin"></i> Pedidos</p>

<nav class="breadcrumb">
  <a href="<%= admin_orders_path %>" class="breadcrumb-item">
    <i class="fa fa-angle-left"></i> pedidos
  </a>
  <span class="breadcrumb-item">historial</span>
</nav>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Cuando</th>
        <th>Usuario</th>
        <th>Cantidad</th>
        <th>Precio</th>
        <th>Método de pago</th>
        <th>Status</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to formatted_date(order.created_at), admin_order_path(order) %></td>
          <td><%= order.user.email %></td>
          <td><%= btc_amount(order.amount) %></td>
          <td><%= number_to_currency order.price, precision: 0 %></td>
          <td><%= order.payment_method.name %></td>
          <!--<td><%= render 'admin/orders/message_count', order: order %></td> -->
          <td><%= order.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% if @orders.count == 0 %>
  <div class="alert alert-info">
    No hay registro de pedidos.
  </div>
<% end %>

<div class="pagination">
  <%= will_paginate @posts, previous_label: 'Previo', next_label: 'Siguiente' %>
</div>

app/views/admin/orders/index.html.erb
<% title 'Pedidos pendientes y nuevos' %>

<p class="page">
  <i class="fa fa-bitcoin"></i> Pedidos
  <a class="btn btn-sm btn-secondary" href="<%= history_admin_orders_path %>">
    <i class="fa fa-history"></i> Ver historial
  </a>
</p>


<p><b><i class="fa fa-folder-o"></i> Pendientes</b></p>
<%= render 'admin/orders/pending' %>

<hr>

<p><b><i class="fa fa-folder-o"></i> Nuevos</b></p>
<%= render 'admin/orders/new' %>

<hr>

<p><b><i class="fa fa-folder-o"></i> Expirados o cancelados recientemente</b></p>
<%= render 'admin/orders/expired' %>

app/views/admin/orders/show.html.erb
<% title "Pedido ##{@order.id}" %>

<p class="page"><i class="fa fa-bitcoin"></i> Pedidos</p>

<nav class="breadcrumb">
  <a href="<%= admin_orders_path %>" class="breadcrumb-item">
    <i class="fa fa-angle-left"></i> pedidos
  </a>
  <span class="breadcrumb-item"><%= "##{@order.id}" %></span>
</nav>

<div class="row">
  <div class="col-sm-6">
    <% if @order.completed %>
      <div class="alert alert-success">
    <% elsif @order.submitted %>
      <div class="alert alert-info">
    <% elsif @order.removed %>
      <div class="alert alert-danger">
    <% elsif @order.expired %>
      <div class="alert alert-warning">
    <% else %>
      <div class="alert alert-info">
    <% end %>
        Status: <b><%= @order.status %></b>
      </div>

    <dl class="row">
      <dt class="col-sm-5">Pedido realizado por</dt>
      <dd class="col-sm-7"><%= link_to @order.user.email, admin_user_path(@order.user) %></dd>
    
      <dt class="col-sm-5">Creado el</dt>
      <dd class="col-sm-7">
        <%= formatted_date(@order.created_at) %> <small class="text-muted">hace <%= time_ago_in_words @order.created_at %></small>
      </dd>
      <% if !@order.completed %>
        <dd class="col-sm-7 offset-sm-5">
          <% if @order.expired %>
            El pedido está expirado <small class="text-muted">Se expiró hace <%= time_ago_in_words @order.expires_at %></small>
            <hr>
            <%= simple_form_for([:admin, @order]) do |f| %>
              <div class="form-group">
                <%= f.hidden_field :removed, value: false %>
                <label><small class="text-muted">Modificar el tiempo de expiración</small></label>
                <%= f.datetime_field :expires_at, class: 'form-control' %>
              </div>
              <%= f.submit 'Actualizar pedido', class: 'btn btn-sm btn-secondary' %>
            <% end %>
            <hr>
          <% else %>
            Se expira <%= formatted_date(@order.expires_at) %> <small class="text-muted">falta <%= distance_of_time_in_words DateTime.current, @order.expires_at %></small>
          <% end %>
        </dd>
      <% end %>

      <dt class="col-sm-5">Cantidad solicitada</dt>
      <dd class="col-sm-7">
        <span class="badge badge-secondary"><%= @order.amount %></span>
        BTC a <span class="badge badge-primary"><%= number_to_currency @order.price, precision: 0 %></span>
      </dd>

      <dt class="col-sm-5">Total</dt>
      <dd class="col-sm-7"><b class="text-success"><%= number_to_currency @order.total, precision: 2, separator: '.' %></b></dd>
    
      <dt class="col-sm-5">Método de pago</dt>
      <dd class="col-sm-7"><%= @order.payment_method.name %></dd> 
      <% if !@order.account_id.blank? %>
        <dd class="col-sm-7 offset-sm-5 <%= 'text-muted' if @account.deprecated? %>">
          <%= @account.name %><br/> 
          <%= @card ? @card.name : "Tarjeta inexistente" %>
          <% if @account.deprecated? %>
            <small class="text-muted">(La cuenta está obsoleta)</small>
          <% end %>
        </dd>

        <dt class="col-sm-5">Cuenta y tarjeta confirmada</dt>
        <dd class="col-sm-7">
          <%= simple_form_for [:admin, @order] do |f| %>
            <%= f.select :confirmed_account_id,
              accounts_collection(true),
              selected: @order.confirmed_account_id || '' %>
            
            <%= f.select :confirmed_card_id,
              cards_collection(true),
              selected: @order.confirmed_card_id || '' %>
            
            <%= f.submit 'Guardar cambios', class: 'btn btn-sm btn-secondary' %>
          <% end %>
        </dd>
      <% else %>
        <dd class="col-sm-7 offset-sm-5">
          <% @order.payment_method.accounts.each do |account| %>
            <% next if !account.bank.active? or !account.active %>

            <%= account.bank.name %> - <%= account.number %>
            <% @order.payment_method.cards.each do |card| %>
              <% if card.active and account.cards.include?(card) %>
                <p><span class="badge badge-default"><%= card.number %></span></p>
              <% end %>
            <% end %> 
          <% end %>
        </dd>
      <% end %> 
    </dl>
    
    <p><b>Domicilio del wallet:</b></p>
    <p class="bg-faded"><code><%= @order.address %></code></p>
    
    <hr>

    <p>Evidencia presentada:</p>

    <% if @order.attachments.count == 0 %>
      <p class="small text-muted">Aun no presentan evidencia.</p>
    <% end %>

    <div class="evidence">
      <% @order.attachments.each do |attachment| %>
        <% if attachment.file.extension == 'pdf' %>
          <p class="pdf-file attachment"><%= link_to 'PDF', attachment.url %></p>
        <% else %>
          <a href="<%= attachment.url %>" data-toggle="modal" data-target="#evidenceModal">
            <%= image_tag attachment.thumb, class: 'attachment img-thumbnail' %>
          </a>
        <% end %>
      <% end %>
    </div>

    <% if @order.submitted and !@order.completed %>
      <hr>
      <div class="">
        <p>Ya transferiste los Bitcoins?</p>
        <%= link_to 'Listo', admin_order_path(complete: true), method: :put, class: 'btn btn-success' %>
      </div>
    
      <hr />

      <p class="text-muted">Quieres rechazar el pedido?</p>
      <%= link_to 'Rechazar', admin_order_path(reject: true), method: :put, class: 'btn btn-sm btn-danger' %>
    <% end %>

    <% if @order.completed %>
      <hr/>
      <p>
        <%= link_to 'Wallet en Blockchain.info', "https://blockchain.info/address/#{@order.address}", target: '_blank', class: 'btn btn-sm btn-warning' %>
      </p>
    <% end %>
    
    <% if !@order.completed %>
      <hr />
      <%= link_to 'Eliminar pedido', admin_order_path(@order),
          method: :delete, data: { confirm: 'El pedido será borrado de la base de datos' },
          class: 'btn btn-sm btn-danger' %>
    <% end %>
  </div>

  <div class="col-sm-6 messages">
    <%= render 'shared/message_feed' %>
  </div>
</div>

<script>
$(document).ready(function() {
  $('.evidence a').on('click', function() {
    var img_src = $(this).prop('href');
    $('#evidenceModal .modal-body img').prop('src', img_src);
  });
});
</script>