config/routes.rb
Rails.application.routes.draw do

  match '/404', to: 'errors#not_found', via: :all
  match '/505', to: 'errors#internal_server_error', via: :all

  devise_for :users, controllers: { registrations: 'registrations' }

  # /comprar (for orders:new)
  resources :orders, except: :new
  match '/comprar', to: 'orders#new', as: :new_order, via: :get

  # message creation route
  resources :messages, only: [:create, :index]

  # notifications
  resources :notifications do
    collection do
      post :mark_as_read
      get :count
    end
  end

  # .../admin/...
  namespace :admin do
    match '/', to: 'dashboard#index', via: :get
    match '/admins', to: 'dashboard#admins', via: :get

    # manage Users, Settings, Account Holders
    
    resources :users

    resources :settings, only: [:index, :update]
    resource :settings, only: [] do 
      post :update_all, on: :member
    end

    resources :account_holders
    
    resources :cards

    # manage Payment Methods + state toggle
    resources :payment_methods do
      collection do
        get 'toggle/:id' => :toggle, as: :toggle
      end
    end

    # manage Orders + history page
    resources :orders do
      collection do
        get 'history' => :history, as: :history
      end
    end

    # manage Orders > Accounts + state toggle
    resources :banks do
      collection do
        get 'toggle/:id' => :toggle, as: :toggle
      end

      resources :accounts do
        collection do
          get 'toggle/:id' => :toggle, as: :toggle
        end
      end
    end
  end

  # logged in  -> account page (orders:index)
  # logged out -> statice home page
  root to: 'pages#home'

  # static pages
  get '/home', to: 'pages#home', as: :home
  get '/instrucciones', to: 'pages#howto', as: :howto
  get '/legal', to: 'pages#legal', as: :legal
  get '/preguntas', to: 'pages#faq', as: :faq
  get '/contacto', to: 'pages#contact', as: :contact
  post '/contacto', to: 'pages#send_message', as: :contact_forms

end

app/views/shared/_flash.html.erb
<% if notice or alert %>
  <div class="flash">
    <div class="container">
      <% @style = 'alert-warning' if alert %>
      <div class="alert alert-success alert-dismissible fade show <%= @style %>">
        <span class="close" data-dismiss="alert">&times;</span>
        <p>
        <% if notice %>
          <%= notice %>
        <% else %>
          <%= alert %>
        <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="container">
    <div class="grid grid--gutters grid--center grid--full large-grid--fit">
      <div class="grid-cell">
        <p><%= link_to 'Privacidad & Legal', legal_path %></p>
        <p><%= link_to '¿Cómo funciona?', howto_path %></p>
      </div>
      <div class="grid-cell">
        <p><%= link_to 'Preguntas Frecuentes', faq_path %></p>
        <p><%= link_to 'Contacto', contact_path %></p>
      </div>
      <div class="grid-cell">
        <div class="made-in-mexico">
          <%= image_tag "madeinmexico.png" %>
        </div>
      </div>
    </div>
    <% if !Setting.phone.blank? %>
      <p class="phone"><%= link_to 'Manda un mensaje a nuestro Whatsapp', contact_path %></p>
    <% end %>
  </div>

</div>

<div class="copyright">
  <p>&copy; 2017 <b>BitAztec</b> Todos los derechos reservados</p>
</div>

app/views/shared/_message.html.erb
<div class="msg media">
  <%= image_tag msg.user.gravatar_url(size: 20, default: 'mm'), class: 'd-flex mr-3' %>
  <div class="media-body">
    <span class="who"><% if current_user == msg.user %>
      Tú
    <% elsif msg.user.admin? %>
      admin
    <% else %>
      <%= msg.user.email %>
    <% end %></span>
    <div class="content <%= 'user' if current_user == msg.user %>">
      <%= msg.body %>
      <span class="small text-muted">Hace <%= time_ago_in_words msg.created_at %></span>
    </div>
  </div>
</div>
<br>

app/views/shared/_message_feed.html.erb
<h5><i class="fa fa-comments"></i> Mensajes</h5>

<% if @order.messages.count == 0 %>
  <p class="text-muted small zero-msgs">Manda un mensaje si tienes alguna duda.</p>
<% end %>

<div class="message-list">
  <% if @order.messages.count == 0 %>
    <p class="empty-messages">...</p>
  <% end %>
  <div class="msgs" data-order="<%= @order.id %>">
    <% @order.messages.each do |msg| %>
      <%= render 'shared/message', msg: msg %> 
    <% end %>
  </div>
</div>

<hr>

<%= form_for(@order.messages.new, html: { class: 'ui reply form' }) do |f| %>
  <%= f.hidden_field :order_id %>
  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', placeholder: 'Escribe aquí...' %>
  </div>
  <button class="btn btn-primary btn-sm">
    <i class="fa fa-send"></i> Enviar  
  </button>
<% end %>

 <script>
$(document).ready(function() {
    $('.message-list').scrollTop($('.message-list')[0].scrollHeight);
  });
 </script> 

app/views/shared/_nav.html.erb
<% page = params[:action] %>

<div class="login">
  <div class="container">
    <div class="float-right">
      <% if !user_signed_in? %>
        <p>
          <%= link_to 'REGISTRO', new_user_registration_path %>
          /
          <%= link_to 'LOGIN', new_user_session_path, class: 'login-link' %>
        </p>
      <% else %>
        <p>
          <% if current_user.admin? %>
            <%= link_to 'ADMIN', admin_path %>
            /
          <% end %>
          <%= link_to 'LOGOUT', destroy_user_session_path, method: :delete, class: 'login-link' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

<div class="nav">
  <div class="container">
    <a class="brand" href="<%= root_path %>">
      <%= image_tag 'logo.png' %>
    </a>

    <ul>
      <li>
        <%= link_to 'Mi cuenta', orders_path, class: "#{'active' if page == 'index'}" %>
      </li>
      <li>
        <%= link_to 'Comprar', new_order_path, class: "#{'active' if page == 'new' and controller_name == 'orders'}" %>
      </li>
      <li>
        <%= link_to '¿Cómo funciona?', howto_path, class: "#{'active' if page == 'howto'}" %>
      </li>
      <li>
        <%= link_to 'FAQ', faq_path, class: "#{'active' if page == 'faq'}" %>
      </li>
      <li>
        <%= link_to 'Acuerdo legal', legal_path, class: "#{'active' if page == 'legal'}" %>
      </li>
      <li>
        <%= link_to 'Contacto', contact_path, class: "#{'active' if page == 'contact'}" %>
      </li>
    </ul>

    <button class="hamburger hamburger--slider" type="button">
      <span class="hamburger-box">
        <span class="hamburger-inner"></span>
      </span>
    </button>

  </div>
</div>