config/routes.rb
Rails.application.routes.draw do

  match '/404', to: 'errors#not_found', via: :all
  match '/505', to: 'errors#internal_server_error', via: :all

  devise_for :users, controllers: { registrations: 'registrations' }

  # /comprar (for orders:new)
  resources :orders, except: :new
  match '/comprar', to: 'orders#new', as: :new_order, via: :get

  # message creation route
  resources :messages, only: [:create, :index]

  # notifications
  resources :notifications do
    collection do
      post :mark_as_read
      get :count
    end
  end

  # .../admin/...
  namespace :admin do
    match '/', to: 'dashboard#index', via: :get
    match '/admins', to: 'dashboard#admins', via: :get

    # manage Users, Settings, Account Holders
    
    resources :users

    resources :settings, only: [:index, :update]
    resource :settings, only: [] do 
      post :update_all, on: :member
    end

    resources :account_holders
    
    resources :cards

    # manage Payment Methods + state toggle
    resources :payment_methods do
      collection do
        get 'toggle/:id' => :toggle, as: :toggle
      end
    end

    # manage Orders + history page
    resources :orders do
      collection do
        get 'history' => :history, as: :history
      end
    end

    # manage Orders > Accounts + state toggle
    resources :banks do
      collection do
        get 'toggle/:id' => :toggle, as: :toggle
      end

      resources :accounts do
        collection do
          get 'toggle/:id' => :toggle, as: :toggle
        end
      end
    end
  end

  # logged in  -> account page (orders:index)
  # logged out -> statice home page
  root to: 'pages#home'

  # static pages
  get '/home', to: 'pages#home', as: :home
  get '/instrucciones', to: 'pages#howto', as: :howto
  get '/legal', to: 'pages#legal', as: :legal
  get '/preguntas', to: 'pages#faq', as: :faq
  get '/contacto', to: 'pages#contact', as: :contact
  post '/contacto', to: 'pages#send_message', as: :contact_forms

end

app/models/bank.rb
class Bank < ApplicationRecord

  default_scope { order(created_at: :desc) }
  validates :name, presence: true
  
  has_many :accounts, dependent: :destroy

  mount_uploader :image, ImageUploader
end

app/controllers/admin/banks_controller.rb
class Admin::BanksController < Admin::BaseController

  before_action :set_bank, except: [:index, :new, :create]

  def index
    @banks = Bank.all
  end

  def show
  end

  def edit
  end

  def new
    @bank = Bank.new
  end

  def create
    @bank = Bank.create(bank_params)
    if @bank.save
      redirect_to admin_banks_path, notice: "Banco '#{@bank.name}' agregado."
    else
      render :new
    end
  end

  def update
    if @bank.update_attributes(bank_params)
      redirect_to admin_banks_path, notice: "Los datos de '#{@bank.name}' fueron actualizados."
    else
      render :edit
    end
  end

  def destroy
    if @bank.destroy
      redirect_to admin_banks_path, notice: "El banco '#{@bank.name} fue eliminado.'"
    end
  end

  def toggle
    # direct db update
    @bank.toggle!(:active)
    redirect_to :back
  end

  private

    def set_bank
      @bank = Bank.find(params[:id])
    end

    def bank_params
      params.require(:bank).permit(:name, :active, :image)
    end

end

app/views/admin/banks/_form.html.erb
<%= simple_form_for([:admin, bank],
                    defaults: { wrapper_html: { class: 'field' } }, 
                    html: { class: 'form' }) do |f| %>
                    
  <div class="form-group">
    <%= f.input :name, autofocus: true, input_html: { class: 'form-control' } %>
  </div>  
  <div class="form-check">
    <label class="form-check-label">
      <%= f.check_box :active, class: 'form-check-input' %>
      <%= f.label :active %>
    </label>
  </div>  
  <div class="form-group">
    <%= f.input :image, as: :file, input_html: { class: 'form-control' } %>
  </div>  
  <div class="form-group">
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>  

<% end %>

app/views/admin/banks/edit.html.erb
<% title 'Bancos' %>

<p class="page"><i class="fa fa-bank"></i> Bancos</p>

<nav class="breadcrumb">
  <a href="<%= admin_banks_path %>" class="breadcrumb-item">
    <i class="fa fa-angle-left"></i> bancos
  </a>
  <span class="breadcrumb-item active"><%= @bank.name %></span>
</nav>

<div class="row justify-content-lg-center">
  <div class="col-lg-6">
    <%= render 'form', bank: @bank %>
  </div>
</div>

app/views/admin/banks/index.html.erb
<%= title 'Bancos' %>

<p>
  <span class="page"><i class="fa fa-bank"></i> Bancos</span>
  <a href="<%= new_admin_bank_path %>" class="nav-link float-right no-mg">
    <i class="fa fa-plus"></i> Banco nuevo
  </a>
</p>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Estado</th>
        <th># de cuentas</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @banks.each do |bank| %>
        <tr>
          <td><%= link_to bank.name, admin_bank_accounts_path(bank) %></td>
          <td>
            <%=
              render 'admin/shared/status_toggle',
                object: bank,
                path: toggle_admin_banks_path(bank) %>
          </td>
          <td><%= bank.accounts.count %></td>
          <td>
            <div class="btn-group">
              <a href="<%= edit_admin_bank_path(bank) %>"
                 class="btn btn-sm btn-secondary">
                <i class="fa fa-edit"></i>
              </a>
              <!--<a class="btn btn-sm btn-danger"
                 href="<%= admin_bank_path(bank) %>"
                 data-confirm="Estás seguro?"
                 rel="nofollow"
                 data-method="delete">
                <i class="fa fa-trash"></i>
              </a>-->
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/banks/new.html.erb
<% title 'Bancos' %>

<p class="page"><i class="fa fa-bank"></i> Bancos</p>

<nav class="breadcrumb">
  <a href="<%= admin_banks_path %>" class="breadcrumb-item">
    <i class="fa fa-angle-left"></i> bancos
  </a>
  <span class="breadcrumb-item active">banco nuevo</span>
</nav>

<div class="row justify-content-lg-center">
  <div class="col-lg-6">
    <%= render 'form', bank: @bank %>
  </div>
</div>